project_id: "yuga-xxx"
instance_type: "n2-standard-4"
zone: "us-central1-a"
image_family: "rhel-8"
image_project: "rhel-cloud"
disk_size: 150
extra_disk_size: 250
new_disk_name: "new-boot-disk"
new_image: "rhel-9-v20240415"
disk_type: "pd-balanced"
sh_user: "xxx"  # or whatever user you use
ssh_wait_time: 30     # seconds to wait for SSH to be available

yba:
  yba_host: "https://xx.184.240.7/"
  customer_id: "customer_id"
  yba_api_token: "api_token"
  universe_name: "xx"
  node_list:
    - ip: "10.128.15.xxx"
      yba_node_name: "yb-dev-TU-n1"  # YBA node name
    - ip: "10.128.0.x"
      yba_node_name: "yb-dev-TU-n2"  # YBA node name
    - ip: "10.128.0.x"
      yba_node_name: "yb-dev-TU-n3"  # YBA node name
  yba_cli_path: "/opt/yugabyte/software/active/yb-platform/yugaware/yba-cli/yba_cli-2024.2.2.2-b2-linux-amd64/yba"
