project_id: "project" 
instance_type: "n2-standard-4"
zone: "us-central1-a"
image_family: "rhel-8"
image_project: "rhel-cloud"
disk_size: 150
extra_disk_size: 250
new_disk_name: "new-boot-disk"
new_image: "rhel-9-v20240415"
disk_type: "pd-balanced"
sh_user: "sh_user"  # or whatever user you use
ssh_wait_time: 30     # seconds to wait for SSH to be available

yba:
  yba_host: "https://xx.xxx.xx.xxx/"
  customer_id: "customer_id"
  yba_api_token: "api_token"
  universe_name: "universe_name"
  node_list:
    - "10.128.15.xxx": "yb-dev-TU1-n4"
  yba_cli_path: "/opt/yugabyte/software/active/yb-platform/yugaware/yba-cli/yba_cli-2024.2.2.2-b2-linux-amd64/yba"
